import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'en' | 'bn';

const en = {
  // ── App-wide ──────────────────────────────────────────────────────────────
  appName: 'Bashabari',
  login: 'Login',
  signup: 'Sign Up',
  loginSignup: 'Login / Sign Up',
  logout: 'Logout',
  back: 'Back',
  cancel: 'Cancel',
  save: 'Save Changes',
  submit: 'Submit',
  done: 'Done',
  continue: 'Continue',
  confirm: 'Confirm',
  viewMore: 'View More',
  menu: 'Menu',
  accessFeatures: 'Access your features',
  online: 'Online',
  sponsored: 'Sponsored',
  verified: 'Verified',
  pending: 'Pending',
  paid: 'Paid',
  language: 'Language',
  english: 'English',
  bangla: 'বাংলা',

  // ── Landing Page ──────────────────────────────────────────────────────────
  heroTagline: "Bangladesh's Most Trusted Rental Platform",
  heroTitle: 'Welcome to',
  heroDesc: 'Creating transparency between Landlords and Tenants through convenient services and legal protection. Find your perfect home or reliable tenants with confidence.',
  getStarted: 'Get Started',
  browseProperties: 'Browse Properties',
  whyChooseUs: 'Why Choose Us',
  whyChooseTitle: 'Why Choose Bashabari?',
  feature1Title: 'Legal Protection',
  feature1Desc: 'Digital agreements and legal rights awareness for both parties',
  feature2Title: 'Verified Listings',
  feature2Desc: 'All properties verified with legal documents and owner verification',
  feature3Title: 'Direct Communication',
  feature3Desc: 'Chat directly with landlords or tenants in-app',
  trustedPartners: 'Our Trusted Partners',
  clientsSay: 'What Our Clients Say',
  ctaTitle: 'So why the wait? Join us',
  ctaDesc: 'Start your journey to finding the perfect home or tenant today',
  createAccount: 'Create Account Now',
  footerTagline: 'Transparency. Convenience. Legal Protection.',
  footerCopy: '© 2026 Bashabari. All rights reserved.',
  reviewTenant: 'Tenant',
  reviewLandlord: 'Landlord',
  reviewStudent: 'Student',

  // ── Auth Page ─────────────────────────────────────────────────────────────
  welcomeBack: 'Welcome Back',
  createAccountTitle: 'Create Account',
  loginDesc: 'Login to access your account',
  signupDesc: 'Join Bashabari to find your perfect home or tenant',
  demoCredentials: 'Demo Credentials',
  iAmA: 'I am a',
  tenantRole: 'Tenant',
  landlordRole: 'Landlord',
  tenantLooking: 'Tenant (Looking for home)',
  landlordRenting: 'Landlord (Renting property)',
  emailAddress: 'Email Address',
  password: 'Password',
  fullName: 'Full Name',
  phoneNumber: 'Phone Number',
  additionalPhone: 'Additional Phone (Optional)',
  currentAddress: 'Current Address',
  occupation: 'Occupation',
  gender: 'Gender',
  maritalStatus: 'Marital Status',
  salary: 'Current Salary (BDT)',
  tenantScore: 'Tenant Score',
  nextPayment: 'Next: Payment & Verification',
  step2Title: 'Step 2: Payment & Verification',
  step2Desc: 'Add payment methods and verify your identity',
  bkash: 'bKash Number',
  nagad: 'Nagad Number',
  bankAccount: 'Bank Account (Optional)',
  physicalVerification: 'Physical Verification',
  uploadDocs: 'Upload documents to get verified badge',
  uploadNid: 'Upload NID',
  uploadBirth: 'Upload Birth Certificate',
  uploadTrade: 'Upload Trade License',
  completeSignup: 'Complete Sign Up',
  student: 'Student',
  bachelor: 'Bachelor',
  professional: 'Professional',
  businessman: 'Businessman',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  single: 'Single',
  married: 'Married',

  // ── Tenant Dashboard ──────────────────────────────────────────────────────
  welcomeBack2: 'Welcome back',
  findHomeToday: 'Find your perfect home today',
  tenantScoreLabel: 'Your Tenant Score',
  identityConfirmed: 'Identity confirmed',
  searchForHomes: 'Search for Homes',
  whatLooking: 'What are you looking for?',
  findFromVerified: 'Find your perfect home from verified listings',
  mostReviewed: 'Most Reviewed Properties Nearby',
  manageProperties: 'Manage your properties and find reliable tenants',
  specialDiscounts: 'Special discounts for Bashabari users',
  exclusiveDeals: 'Exclusive deals for Bashabari landlords',
  services: 'Services',
  writtenAgreements: 'Written Agreements',
  transactions: 'Transactions',
  ratings: 'Ratings',
  legalRights: 'Legal Rights',
  bookedFlats: 'Booked Flats',
  moveInHelp: 'Move-in help & premium features',
  viewAgreements: 'View all your rental agreements',
  billHistory: 'Monthly rent & bill history',
  reviewHomes: 'Review your previous homes',
  earn100: 'Earn 100 BDT',
  knowTenantRights: 'Know your tenant rights',
  savedProperties: 'Your saved properties',
  myPosts: 'My Posts',
  manageListings: 'Manage your property listings',
  checkReviews: 'Check reviews on your properties',
  knowLandlordRights: 'Know your landlord rights',
  rentCollectionHistory: 'Monthly rent & bill collection history',
  viewAllAgreements: 'View all rental agreements with tenants',

  // ── Landlord Dashboard ────────────────────────────────────────────────────
  activeListings: 'Active Listings',
  verifiedPosts: 'Verified Posts',
  totalTenants: 'Total Tenants',
  avgRating: 'Avg Rating',
  readyToRent: 'Ready to rent your property?',
  postAndFind: 'Post your property and find verified tenants quickly',
  postNewProperty: 'Post New Property',
  viewMyPosts: 'View My Posts',
  quickActions: 'Quick Actions',
  recentActivity: 'Recent Activity',
  newInquiry: 'New inquiry received',
  newInquiryDesc: 'Someone interested in your Gulshan apartment',
  rentReceived: 'Rent payment received',
  rentReceivedDesc: '25,000 BDT from Banani property tenant',
  propertyVerified: 'Property verified',
  propertyVerifiedDesc: 'Your Dhanmondi listing is now verified',
  hoursAgo: 'hours ago',
  dayAgo: 'day ago',
  daysAgo: 'days ago',

  // ── Property Search ───────────────────────────────────────────────────────
  propertySearch: 'Property Search',
  whatAreYouLooking: 'What are you looking for?',
  selectTypeDesc: 'Select the type of property you need',
  family: 'Family',
  familyDesc: 'Apartments & villas for families',
  students: 'Students',
  studentsDesc: 'Affordable housing for students',
  bachelors: 'Bachelors',
  bachelorsDesc: 'Single rooms & studio flats',
  commercial: 'Commercial',
  commercialDesc: 'Offices, shops & showrooms',
  refineSearch: 'Refine Your Search',
  refineDesc: 'Choose property type and set your preferences',
  propertyType: 'Property Type',
  budgetRange: 'Budget Range',
  preferredLocation: 'Preferred Location',
  searchProperties: 'Search Properties',
  availableProperties: 'Available Properties',
  propertiesFound: 'properties found',
  refineSearchBtn: 'Refine Search',
  contact: 'Contact',
  bedroom: 'Bedroom',
  bedrooms: 'Bedrooms',
  bathroom: 'Bathroom',
  bathrooms: 'Bathrooms',

  // ── Property Details ──────────────────────────────────────────────────────
  propertyDetails: 'Property Details',
  propertyDetailsTitle: 'Property Details',
  monthlyRent: 'Monthly Rent',
  waterBill: 'Water Bill',
  electricityBill: 'Electricity Bill',
  gasBill: 'Gas Bill',
  ownerInfo: 'Owner Information',
  ownerRating: 'owner rating',
  contactOwner: 'Contact Owner',
  aboutProperty: 'About This Property',
  reviewsSection: 'Reviews',
  leaveReview: 'Leave a Review',
  earn100Review: '💰 Earn 100 BDT for your review!',
  submitReview: 'Submit Review',
  saveProperty: 'Save Property',
  bookToConfirm: 'Book to Confirm',
  approxWater: '500 BDT (approx.)',
  asPerUsage: 'As per usage',
  included: 'Included',

  // ── Property Post ─────────────────────────────────────────────────────────
  postYourProperty: 'Post Your Property',
  propertyInfo: 'Property Information',
  fillDetails: 'Fill in the details about your property',
  propertyPhotos: 'Property Photos',
  uploadClearPics: 'Upload clear pictures of all rooms (up to 6 photos)',
  addPhoto: 'Add Photo',
  legalDocuments: 'Legal Documents',
  uploadOwnership: 'Upload proof of ownership',
  addMoreDocs: 'Add More Documents',
  uploadOwnershipDocs: 'Upload Ownership Documents',
  basicDetails: 'Basic Details',
  yourName: 'Your Name',
  location: 'Location',
  religionPreference: 'Religion Preference (Optional)',
  preferredTenant: 'Preferred Tenant',
  propertyDescription: 'Property Description (Max 1500 words)',
  pricingDetails: 'Pricing Details',
  continuePostOptions: 'Continue to Post Options',
  choosePostType: 'Choose Post Type',
  selectListingType: 'Select how you want to list your property',
  freePost: 'Free Post',
  freeBDT: '0 BDT',
  freeDesc: 'Basic listing without verification',
  listedImmediately: 'Listed immediately',
  standardReach: 'Standard reach',
  noVerificationBadge: 'No verification badge',
  lowerPriority: 'Lower priority in search',
  verifiedPostTitle: 'Verified Post ⭐',
  verifiedBDT: '200 BDT',
  verifiedDesc: 'Premium listing with verification',
  verifiedBadge: 'Verified badge displayed',
  prioritySearch: 'Priority in search results',
  guaranteedWeek: 'Guaranteed within 1 week',
  docVerification: 'Official document verification',
  proceedPayment: 'Proceed to Payment',
  postProperty: 'Post Property',
  completePayment: 'Complete Payment',
  pay200: 'Pay 200 BDT for verified posting',
  paymentMethod: 'Payment Method',
  transactionId: 'Transaction ID',
  confirmPayment: 'Confirm Payment',
  propertyPosted: 'Property Posted!',
  paymentReceived: 'Payment Received!',
  backToDashboard: 'Back to Dashboard',
  any: 'Any',
  muslim: 'Muslim',
  hindu: 'Hindu',
  buddhist: 'Buddhist',
  christian: 'Christian',

  // ── Profile ───────────────────────────────────────────────────────────────
  myProfile: 'My Profile',
  editProfile: 'Edit Profile',
  personalInfo: 'Personal Information',
  paymentMethods: 'Payment Methods',
  verificationDocs: 'Verification Documents',
  fullNameLabel: 'Full Name',
  emailLabel: 'Email',
  phoneLabel: 'Phone Number',
  additionalPhoneLabel: 'Additional Phone',
  addressLabel: 'Current Address',
  occupationLabel: 'Occupation',
  genderLabel: 'Gender',
  maritalStatusLabel: 'Marital Status',
  currentSalary: 'Current Salary',
  monthlySaving: 'Monthly Saving',
  bankAccountLabel: 'Bank Account (Optional)',
  nationalId: 'National ID (NID)',
  birthCertificate: 'Birth Certificate',
  tradeLicense: 'Trade License',
  view: 'View',
  uploadPhoto: 'Upload Photo',
  profilePicture: 'Profile Picture',

  // ── Services ──────────────────────────────────────────────────────────────
  servicesTitle: 'Services',
  moveIn: 'Move In',
  moveInDesc: 'Complete settlement assistance for your new home with furniture transit, electronics setup, and WiFi installation.',
  premiumTitle: 'Bashabari Premium',
  premiumDesc: 'Unlock exclusive benefits and protection for your rental journey',
  yearBackup: '1 Year Free Backup Service',
  yearBackupDesc: 'Emergency support and maintenance assistance 24/7',
  yearRentLock: '1 Year Rent Price Lock Guarantee',
  yearRentLockDesc: 'Your rent stays the same for the entire year',
  yearLegal: '1 Year Free Legal Backup',
  yearLegalDesc: 'Professional legal support for any rental disputes',
  oneTimeAnnual: 'One-time annual payment',
  purchasePremium: 'Purchase Premium',

  // ── Chat ──────────────────────────────────────────────────────────────────
  chatPlaceholder: 'Type a message...',
  contactOwnerChat: 'Contact Owner',

  // ── Transactions ──────────────────────────────────────────────────────────
  transactionHistory: 'Transaction History',
  totalPaid: 'Total Paid (2026)',
  pendingPayments: 'Pending Payments',
  avgMonthly: 'Avg Monthly Expense',
  allTransactions: 'All Transactions',
  monthlyBreakdown: 'Monthly Breakdown',
  payNow: 'Pay Now',
  downloadReceipt: 'Receipt',
  downloadStatement: 'Download Statement',
  dueBy: 'Due by June 10',
  last3Months: 'Last 3 months',
  transactionsCompleted: 'transactions completed',
  date: 'Date',
  method: 'Method',
  txId: 'TX ID',
  total: 'Total',
  rent: 'Rent',

  // ── Ratings ───────────────────────────────────────────────────────────────
  rateProperties: 'Rate Your Properties',
  earn100Each: 'Earn 100 BDT for Each Review!',
  earn100Desc: 'Share your experience and get 100 BDT credited to your bKash/Nagad account after review approval.',
  rateThisProperty: 'Rate this property:',
  writeReview: 'Write your review:',
  earn100Banner: 'Earn 100 BDT!',
  earn100Submit: 'Submit your honest review and get 100 BDT credited to your mobile wallet within 24 hours.',
  submitAndEarn: 'Submit Review & Earn 100 BDT',
  yourRating: 'Your Rating:',
  yourReview: 'Your Review:',
  rewardCredited: 'Reward Credited!',
  rewardCreditedDesc: '100 BDT has been credited to your mobile wallet.',
  editReview: 'Edit Review',
  tenantRating: 'Tenant Rating:',
  reviewText: 'Review:',
  receivedBDT: 'You received 100 BDT from Bashabari',

  // ── Agreements ────────────────────────────────────────────────────────────
  writtenAgreementsTitle: 'Written Agreements',
  digitalAgreements: 'Digital Agreements',
  digitalAgreementsDesc: 'All your rental agreements are stored securely. You can view, download, or share them anytime.',
  activeStatus: 'Active',
  expiredStatus: 'Expired',
  landlordLabel: 'Landlord',
  tenantLabel: 'Tenant',
  startDate: 'Start Date',
  endDate: 'End Date',
  signedOn: 'Signed On',
  monthlyRentLabel: 'Monthly Rent',
  advancePayment: 'Advance Payment',
  securityDeposit: 'Security Deposit',
  keyTerms: 'Key Terms & Conditions',
  viewFull: 'View Full Agreement',
  downloadPdf: 'Download PDF',

  // ── Booked Flats ──────────────────────────────────────────────────────────
  bookedProperties: 'Booked Properties',
  savedPropertiesTitle: 'Your Saved Properties',
  savedPropertiesDesc: 'Properties you\'ve shown interest in. Contact the owners directly through the app.',
  ownerContact: 'Owner Contact',
  saved: 'Saved',
  viewDetails: 'View Details',

  // ── Legal Rights ──────────────────────────────────────────────────────────
  legalRightsTitle: 'Legal Rights',
  tenantRightsTitle: 'Your Rights as a Tenant',
  landlordRightsTitle: 'Your Rights as a Landlord',
  legalDesc: 'Know your legal rights and protections under Bangladesh rental laws',
  importantInfo: 'Important Information',
  legalNote: 'These rights are based on the Premises Rent Control Act and related housing regulations in Bangladesh. Always document agreements in writing.',
  needLegal: 'Need Legal Assistance?',
  needLegalDesc: "If you're facing a legal issue, consult with a lawyer or contact the Rent Controller office in your area.",
  contactSupport: 'Contact Support',

  // ── Move In ───────────────────────────────────────────────────────────────
  moveInService: 'Move In Service',
  moveInDetails: 'Move In Details',
  propertiesViewed: 'Properties You Viewed',
  selectPropertyDesc: 'Select a property to begin your move-in process',
  helpSettle: 'Help Me Settle In',
  settleDesc: 'Select the services you need for a smooth move-in',
  electronicsSetup: 'Electronics Set-up',
  electronicsDesc: 'Professional installation of TV, AC, and appliances',
  furnitureTransit: 'Furniture Transit',
  furnitureDesc: 'Safe moving and arrangement of furniture',
  wifiInstall: 'WiFi Installation',
  wifiDesc: 'High-speed internet setup and configuration',
  addIn: 'Add-in',
  added: '✓ Added',
  totalCost: 'Total Cost:',
  confirmMoveIn: 'Confirm Move In',
  moveInSent: 'Move In Request Sent!',
  moveInSentDesc: 'Your confirmation message has been sent to {owner}. Please check the chatbox for their response.',
  goToChatbox: 'Go to Chatbox',

  // ── Premium Payment ───────────────────────────────────────────────────────
  premiumSubscription: 'Premium Subscription',
  premiumAnnual: 'Bashabari Premium — Annual Subscription',
  subscriptionPeriod: 'Subscription Period:',
  oneYear: '1 Year',
  amount: 'Amount:',
  selectPaymentMethod: 'Select Payment Method',
  paymentInfo: 'Payment Information',
  mobileNumber: 'Mobile Number',
  txIdLabel: 'Transaction ID',
  payAmount: 'Pay',
  paymentSuccess: 'Payment Successful!',
  welcomePremium: 'Welcome to Bashabari Premium!',
  premiumActive: 'Your premium subscription is now active. Enjoy all the exclusive benefits for the next 12 months.',

  // ── Payment Interface ─────────────────────────────────────────────────────
  makePayment: 'Make Payment',
  paymentDetailsTitle: 'Payment Details',
  property: 'Property',
  paymentType: 'Payment Type',
  dueDate: 'Due Date',
  amountLabel: 'Amount:',
  accountNumber: 'Account Number',
  pin: 'PIN / Password',
  enterPin: 'Enter your PIN',
  paymentReceivedMsg: 'has been successfully paid',

  // ── My Posts ──────────────────────────────────────────────────────────────
  myPostsTitle: 'My Posts',
  verifiedTab: 'Verified',
  pendingTab: 'Pending',
  unverifiedTab: 'Unverified',
  views: 'Views',
  inquiries: 'Inquiries',
  postedOn: 'Posted on',
  edit: 'Edit',
  noVerifiedPosts: 'No Verified Posts',
  noVerifiedDesc: 'Your verified posts will appear here',
  noPendingPosts: 'No Pending Posts',
  noPendingDesc: 'Posts awaiting verification will appear here',
  noUnverifiedPosts: 'No Unverified Posts',
  noUnverifiedDesc: 'Your free posts will appear here',
  underReview: 'Under Review',
} as const;

const bn: typeof en = {
  // ── App-wide ──────────────────────────────────────────────────────────────
  appName: 'বাসাবাড়ি',
  login: 'লগইন',
  signup: 'নিবন্ধন',
  loginSignup: 'লগইন / নিবন্ধন',
  logout: 'লগআউট',
  back: 'পেছনে',
  cancel: 'বাতিল',
  save: 'পরিবর্তন সংরক্ষণ',
  submit: 'জমা দিন',
  done: 'সম্পন্ন',
  continue: 'চালিয়ে যান',
  confirm: 'নিশ্চিত করুন',
  viewMore: 'আরও দেখুন',
  menu: 'মেনু',
  accessFeatures: 'আপনার সুবিধাগুলি অ্যাক্সেস করুন',
  online: 'অনলাইন',
  sponsored: 'বিজ্ঞাপন',
  verified: 'যাচাইকৃত',
  pending: 'মুলতুবি',
  paid: 'পরিশোধিত',
  language: 'ভাষা',
  english: 'English',
  bangla: 'বাংলা',

  // ── Landing Page ──────────────────────────────────────────────────────────
  heroTagline: 'বাংলাদেশের সবচেয়ে বিশ্বস্ত ভাড়া প্ল্যাটফর্ম',
  heroTitle: 'স্বাগতম',
  heroDesc: 'বাড়িওয়ালা ও ভাড়াটেদের মধ্যে স্বচ্ছতা তৈরি করছে বাসাবাড়ি — সুবিধাজনক সেবা ও আইনি সুরক্ষার মাধ্যমে। আস্থার সাথে আপনার নিখুঁত বাড়ি বা নির্ভরযোগ্য ভাড়াটে খুঁজুন।',
  getStarted: 'শুরু করুন',
  browseProperties: 'বাড়ি দেখুন',
  whyChooseUs: 'কেন আমাদের বেছে নেবেন',
  whyChooseTitle: 'কেন বাসাবাড়ি বেছে নেবেন?',
  feature1Title: 'আইনি সুরক্ষা',
  feature1Desc: 'উভয় পক্ষের জন্য ডিজিটাল চুক্তি এবং আইনি অধিকার সচেতনতা',
  feature2Title: 'যাচাইকৃত তালিকা',
  feature2Desc: 'সমস্ত বাড়ি আইনি নথি ও মালিক যাচাইয়ের মাধ্যমে নিশ্চিত',
  feature3Title: 'সরাসরি যোগাযোগ',
  feature3Desc: 'অ্যাপের মধ্যেই বাড়িওয়ালা বা ভাড়াটের সাথে সরাসরি চ্যাট করুন',
  trustedPartners: 'আমাদের বিশ্বস্ত অংশীদার',
  clientsSay: 'আমাদের ক্লায়েন্টরা কী বলেন',
  ctaTitle: 'তাহলে দেরি কেন? আমাদের সাথে যোগ দিন',
  ctaDesc: 'আজই শুরু করুন আপনার নিখুঁত বাড়ি বা ভাড়াটে খোঁজার যাত্রা',
  createAccount: 'এখনই একাউন্ট তৈরি করুন',
  footerTagline: 'স্বচ্ছতা। সুবিধা। আইনি সুরক্ষা।',
  footerCopy: '© ২০২৬ বাসাবাড়ি। সর্বস্বত্ব সংরক্ষিত।',
  reviewTenant: 'ভাড়াটে',
  reviewLandlord: 'বাড়িওয়ালা',
  reviewStudent: 'ছাত্র',

  // ── Auth Page ─────────────────────────────────────────────────────────────
  welcomeBack: 'ফিরে আসায় স্বাগতম',
  createAccountTitle: 'একাউন্ট তৈরি করুন',
  loginDesc: 'আপনার একাউন্টে লগইন করুন',
  signupDesc: 'বাসাবাড়িতে যোগ দিন এবং আপনার নিখুঁত বাড়ি বা ভাড়াটে খুঁজুন',
  demoCredentials: 'ডেমো তথ্য',
  iAmA: 'আমি একজন',
  tenantRole: 'ভাড়াটে',
  landlordRole: 'বাড়িওয়ালা',
  tenantLooking: 'ভাড়াটে (বাড়ি খুঁজছি)',
  landlordRenting: 'বাড়িওয়ালা (বাড়ি ভাড়া দিচ্ছি)',
  emailAddress: 'ইমেইল ঠিকানা',
  password: 'পাসওয়ার্ড',
  fullName: 'পুরো নাম',
  phoneNumber: 'ফোন নম্বর',
  additionalPhone: 'অতিরিক্ত ফোন (ঐচ্ছিক)',
  currentAddress: 'বর্তমান ঠিকানা',
  occupation: 'পেশা',
  gender: 'লিঙ্গ',
  maritalStatus: 'বৈবাহিক অবস্থা',
  salary: 'বর্তমান বেতন (টাকা)',
  tenantScore: 'ভাড়াটে স্কোর',
  nextPayment: 'পরবর্তী: পেমেন্ট ও যাচাইকরণ',
  step2Title: 'ধাপ ২: পেমেন্ট ও যাচাইকরণ',
  step2Desc: 'পেমেন্ট পদ্ধতি যোগ করুন এবং আপনার পরিচয় যাচাই করুন',
  bkash: 'বিকাশ নম্বর',
  nagad: 'নগদ নম্বর',
  bankAccount: 'ব্যাংক একাউন্ট (ঐচ্ছিক)',
  physicalVerification: 'শারীরিক যাচাইকরণ',
  uploadDocs: 'যাচাইকৃত ব্যাজ পেতে নথিপত্র আপলোড করুন',
  uploadNid: 'জাতীয় পরিচয়পত্র আপলোড করুন',
  uploadBirth: 'জন্ম সনদ আপলোড করুন',
  uploadTrade: 'ট্রেড লাইসেন্স আপলোড করুন',
  completeSignup: 'নিবন্ধন সম্পন্ন করুন',
  student: 'ছাত্র',
  bachelor: 'ব্যাচেলর',
  professional: 'পেশাদার',
  businessman: 'ব্যবসায়ী',
  male: 'পুরুষ',
  female: 'মহিলা',
  other: 'অন্যান্য',
  single: 'অবিবাহিত',
  married: 'বিবাহিত',

  // ── Tenant Dashboard ──────────────────────────────────────────────────────
  welcomeBack2: 'স্বাগতম',
  findHomeToday: 'আজই আপনার নিখুঁত বাড়ি খুঁজুন',
  tenantScoreLabel: 'আপনার ভাড়াটে স্কোর',
  identityConfirmed: 'পরিচয় নিশ্চিত',
  searchForHomes: 'বাড়ি অনুসন্ধান করুন',
  whatLooking: 'আপনি কী খুঁজছেন?',
  findFromVerified: 'যাচাইকৃত তালিকা থেকে আপনার নিখুঁত বাড়ি খুঁজুন',
  mostReviewed: 'কাছের সর্বাধিক পর্যালোচিত বাড়ি',
  manageProperties: 'আপনার বাড়ি পরিচালনা করুন এবং নির্ভরযোগ্য ভাড়াটে খুঁজুন',
  specialDiscounts: 'বাসাবাড়ি ব্যবহারকারীদের জন্য বিশেষ ছাড়',
  exclusiveDeals: 'বাসাবাড়ি বাড়িওয়ালাদের জন্য বিশেষ অফার',
  services: 'সেবাসমূহ',
  writtenAgreements: 'লিখিত চুক্তি',
  transactions: 'লেনদেন',
  ratings: 'রেটিং',
  legalRights: 'আইনি অধিকার',
  bookedFlats: 'সংরক্ষিত ফ্ল্যাট',
  moveInHelp: 'স্থানান্তর সহায়তা ও প্রিমিয়াম সুবিধা',
  viewAgreements: 'আপনার সমস্ত ভাড়া চুক্তি দেখুন',
  billHistory: 'মাসিক ভাড়া ও বিল ইতিহাস',
  reviewHomes: 'আপনার আগের বাড়িগুলো পর্যালোচনা করুন',
  earn100: '১০০ টাকা আয় করুন',
  knowTenantRights: 'ভাড়াটে হিসেবে আপনার অধিকার জানুন',
  savedProperties: 'আপনার সংরক্ষিত বাড়িসমূহ',
  myPosts: 'আমার পোস্ট',
  manageListings: 'আপনার বাড়ির তালিকা পরিচালনা করুন',
  checkReviews: 'আপনার বাড়ির পর্যালোচনা দেখুন',
  knowLandlordRights: 'বাড়িওয়ালা হিসেবে আপনার অধিকার জানুন',
  rentCollectionHistory: 'মাসিক ভাড়া ও বিল সংগ্রহের ইতিহাস',
  viewAllAgreements: 'ভাড়াটেদের সাথে সমস্ত ভাড়া চুক্তি দেখুন',

  // ── Landlord Dashboard ────────────────────────────────────────────────────
  activeListings: 'সক্রিয় তালিকা',
  verifiedPosts: 'যাচাইকৃত পোস্ট',
  totalTenants: 'মোট ভাড়াটে',
  avgRating: 'গড় রেটিং',
  readyToRent: 'আপনার বাড়ি ভাড়া দিতে প্রস্তুত?',
  postAndFind: 'আপনার বাড়ি পোস্ট করুন এবং দ্রুত যাচাইকৃত ভাড়াটে খুঁজুন',
  postNewProperty: 'নতুন বাড়ি পোস্ট করুন',
  viewMyPosts: 'আমার পোস্ট দেখুন',
  quickActions: 'দ্রুত অ্যাকশন',
  recentActivity: 'সাম্প্রতিক কার্যক্রম',
  newInquiry: 'নতুন অনুসন্ধান পাওয়া গেছে',
  newInquiryDesc: 'কেউ আপনার গুলশান অ্যাপার্টমেন্টে আগ্রহী',
  rentReceived: 'ভাড়া পেমেন্ট পাওয়া গেছে',
  rentReceivedDesc: 'বনানী বাড়ির ভাড়াটে থেকে ২৫,০০০ টাকা পেয়েছেন',
  propertyVerified: 'বাড়ি যাচাইকৃত হয়েছে',
  propertyVerifiedDesc: 'আপনার ধানমন্ডির তালিকা এখন যাচাইকৃত',
  hoursAgo: 'ঘণ্টা আগে',
  dayAgo: 'দিন আগে',
  daysAgo: 'দিন আগে',

  // ── Property Search ───────────────────────────────────────────────────────
  propertySearch: 'বাড়ি অনুসন্ধান',
  whatAreYouLooking: 'আপনি কী খুঁজছেন?',
  selectTypeDesc: 'আপনার প্রয়োজনের ধরন নির্বাচন করুন',
  family: 'পরিবার',
  familyDesc: 'পরিবারের জন্য অ্যাপার্টমেন্ট ও ভিলা',
  students: 'ছাত্রছাত্রী',
  studentsDesc: 'ছাত্রদের জন্য সাশ্রয়ী আবাসন',
  bachelors: 'ব্যাচেলর',
  bachelorsDesc: 'একক কক্ষ ও স্টুডিও ফ্ল্যাট',
  commercial: 'বাণিজ্যিক',
  commercialDesc: 'অফিস, দোকান ও শোরুম',
  refineSearch: 'অনুসন্ধান পরিমার্জন করুন',
  refineDesc: 'বাড়ির ধরন বেছে নিন এবং পছন্দ নির্ধারণ করুন',
  propertyType: 'বাড়ির ধরন',
  budgetRange: 'বাজেট সীমা',
  preferredLocation: 'পছন্দের অবস্থান',
  searchProperties: 'বাড়ি খুঁজুন',
  availableProperties: 'উপলব্ধ বাড়িসমূহ',
  propertiesFound: 'টি বাড়ি পাওয়া গেছে',
  refineSearchBtn: 'পরিমার্জন করুন',
  contact: 'যোগাযোগ',
  bedroom: 'শয়নকক্ষ',
  bedrooms: 'শয়নকক্ষ',
  bathroom: 'বাথরুম',
  bathrooms: 'বাথরুম',

  // ── Property Details ──────────────────────────────────────────────────────
  propertyDetails: 'বাড়ির বিবরণ',
  propertyDetailsTitle: 'বাড়ির বিবরণ',
  monthlyRent: 'মাসিক ভাড়া',
  waterBill: 'পানির বিল',
  electricityBill: 'বিদ্যুৎ বিল',
  gasBill: 'গ্যাস বিল',
  ownerInfo: 'মালিকের তথ্য',
  ownerRating: 'মালিক রেটিং',
  contactOwner: 'মালিকের সাথে যোগাযোগ করুন',
  aboutProperty: 'এই বাড়ি সম্পর্কে',
  reviewsSection: 'পর্যালোচনাসমূহ',
  leaveReview: 'পর্যালোচনা লিখুন',
  earn100Review: '💰 আপনার পর্যালোচনার জন্য ১০০ টাকা আয় করুন!',
  submitReview: 'পর্যালোচনা জমা দিন',
  saveProperty: 'বাড়ি সংরক্ষণ করুন',
  bookToConfirm: 'নিশ্চিত করতে বুক করুন',
  approxWater: '৫০০ টাকা (আনুমানিক)',
  asPerUsage: 'ব্যবহার অনুযায়ী',
  included: 'অন্তর্ভুক্ত',

  // ── Property Post ─────────────────────────────────────────────────────────
  postYourProperty: 'আপনার বাড়ি পোস্ট করুন',
  propertyInfo: 'বাড়ির তথ্য',
  fillDetails: 'আপনার বাড়ির বিস্তারিত তথ্য দিন',
  propertyPhotos: 'বাড়ির ছবি',
  uploadClearPics: 'সমস্ত কক্ষের স্পষ্ট ছবি আপলোড করুন (সর্বোচ্চ ৬টি)',
  addPhoto: 'ছবি যোগ করুন',
  legalDocuments: 'আইনি নথিপত্র',
  uploadOwnership: 'মালিকানার প্রমাণ আপলোড করুন',
  addMoreDocs: 'আরও নথি যোগ করুন',
  uploadOwnershipDocs: 'মালিকানা নথিপত্র আপলোড করুন',
  basicDetails: 'মূল তথ্য',
  yourName: 'আপনার নাম',
  location: 'অবস্থান',
  religionPreference: 'ধর্ম পছন্দ (ঐচ্ছিক)',
  preferredTenant: 'পছন্দের ভাড়াটে',
  propertyDescription: 'বাড়ির বিবরণ (সর্বোচ্চ ১৫০০ শব্দ)',
  pricingDetails: 'মূল্য বিবরণ',
  continuePostOptions: 'পোস্ট অপশনে যান',
  choosePostType: 'পোস্টের ধরন বেছে নিন',
  selectListingType: 'আপনার বাড়ি কীভাবে তালিকাভুক্ত করতে চান তা নির্বাচন করুন',
  freePost: 'বিনামূল্যে পোস্ট',
  freeBDT: '০ টাকা',
  freeDesc: 'যাচাইকরণ ছাড়া মৌলিক তালিকা',
  listedImmediately: 'তাৎক্ষণিকভাবে তালিকাভুক্ত',
  standardReach: 'সাধারণ প্রচার',
  noVerificationBadge: 'কোনো যাচাই ব্যাজ নেই',
  lowerPriority: 'অনুসন্ধানে কম অগ্রাধিকার',
  verifiedPostTitle: 'যাচাইকৃত পোস্ট ⭐',
  verifiedBDT: '২০০ টাকা',
  verifiedDesc: 'যাচাইকরণসহ প্রিমিয়াম তালিকা',
  verifiedBadge: 'যাচাই ব্যাজ প্রদর্শিত হবে',
  prioritySearch: 'অনুসন্ধানে অগ্রাধিকার',
  guaranteedWeek: '১ সপ্তাহের মধ্যে নিশ্চিত',
  docVerification: 'সরকারি নথি যাচাইকরণ',
  proceedPayment: 'পেমেন্টে যান',
  postProperty: 'বাড়ি পোস্ট করুন',
  completePayment: 'পেমেন্ট সম্পন্ন করুন',
  pay200: 'যাচাইকৃত পোস্টের জন্য ২০০ টাকা পরিশোধ করুন',
  paymentMethod: 'পেমেন্ট পদ্ধতি',
  transactionId: 'লেনদেন আইডি',
  confirmPayment: 'পেমেন্ট নিশ্চিত করুন',
  propertyPosted: 'বাড়ি পোস্ট হয়েছে!',
  paymentReceived: 'পেমেন্ট পাওয়া গেছে!',
  backToDashboard: 'ড্যাশবোর্ডে ফিরে যান',
  any: 'যেকোনো',
  muslim: 'মুসলিম',
  hindu: 'হিন্দু',
  buddhist: 'বৌদ্ধ',
  christian: 'খ্রিস্টান',

  // ── Profile ───────────────────────────────────────────────────────────────
  myProfile: 'আমার প্রোফাইল',
  editProfile: 'প্রোফাইল সম্পাদনা',
  personalInfo: 'ব্যক্তিগত তথ্য',
  paymentMethods: 'পেমেন্ট পদ্ধতি',
  verificationDocs: 'যাচাইকরণ নথি',
  fullNameLabel: 'পুরো নাম',
  emailLabel: 'ইমেইল',
  phoneLabel: 'ফোন নম্বর',
  additionalPhoneLabel: 'অতিরিক্ত ফোন',
  addressLabel: 'বর্তমান ঠিকানা',
  occupationLabel: 'পেশা',
  genderLabel: 'লিঙ্গ',
  maritalStatusLabel: 'বৈবাহিক অবস্থা',
  currentSalary: 'বর্তমান বেতন',
  monthlySaving: 'মাসিক সঞ্চয়',
  bankAccountLabel: 'ব্যাংক একাউন্ট (ঐচ্ছিক)',
  nationalId: 'জাতীয় পরিচয়পত্র (NID)',
  birthCertificate: 'জন্ম সনদ',
  tradeLicense: 'ট্রেড লাইসেন্স',
  view: 'দেখুন',
  uploadPhoto: 'ছবি আপলোড করুন',
  profilePicture: 'প্রোফাইল ছবি',

  // ── Services ──────────────────────────────────────────────────────────────
  servicesTitle: 'সেবাসমূহ',
  moveIn: 'স্থানান্তর সেবা',
  moveInDesc: 'আসবাবপত্র পরিবহন, ইলেকট্রনিক্স সেটআপ এবং ওয়াইফাই স্থাপনাসহ আপনার নতুন বাড়িতে সম্পূর্ণ স্থানান্তর সহায়তা।',
  premiumTitle: 'বাসাবাড়ি প্রিমিয়াম',
  premiumDesc: 'আপনার ভাড়ার যাত্রায় এক্সক্লুসিভ সুবিধা ও সুরক্ষা উন্মুক্ত করুন',
  yearBackup: '১ বছর বিনামূল্যে ব্যাকআপ সেবা',
  yearBackupDesc: '২৪/৭ জরুরি সহায়তা ও রক্ষণাবেক্ষণ সহায়তা',
  yearRentLock: '১ বছর ভাড়া মূল্য স্থির গ্যারান্টি',
  yearRentLockDesc: 'পুরো বছর আপনার ভাড়া একই থাকবে',
  yearLegal: '১ বছর বিনামূল্যে আইনি ব্যাকআপ',
  yearLegalDesc: 'যেকোনো ভাড়া বিরোধে পেশাদার আইনি সহায়তা',
  oneTimeAnnual: 'এককালীন বার্ষিক পেমেন্ট',
  purchasePremium: 'প্রিমিয়াম কিনুন',

  // ── Chat ──────────────────────────────────────────────────────────────────
  chatPlaceholder: 'একটি বার্তা লিখুন...',
  contactOwnerChat: 'মালিকের সাথে যোগাযোগ করুন',

  // ── Transactions ──────────────────────────────────────────────────────────
  transactionHistory: 'লেনদেনের ইতিহাস',
  totalPaid: 'মোট পরিশোধিত (২০২৬)',
  pendingPayments: 'মুলতুবি পেমেন্ট',
  avgMonthly: 'গড় মাসিক ব্যয়',
  allTransactions: 'সকল লেনদেন',
  monthlyBreakdown: 'মাসিক বিভাজন',
  payNow: 'এখনই পরিশোধ করুন',
  downloadReceipt: 'রসিদ',
  downloadStatement: 'বিবৃতি ডাউনলোড করুন',
  dueBy: 'পরিশোধের শেষ তারিখ: ১০ জুন',
  last3Months: 'গত ৩ মাস',
  transactionsCompleted: 'টি লেনদেন সম্পন্ন',
  date: 'তারিখ',
  method: 'পদ্ধতি',
  txId: 'TX আইডি',
  total: 'মোট',
  rent: 'ভাড়া',

  // ── Ratings ───────────────────────────────────────────────────────────────
  rateProperties: 'আপনার বাড়ি রেট করুন',
  earn100Each: 'প্রতিটি পর্যালোচনার জন্য ১০০ টাকা আয় করুন!',
  earn100Desc: 'আপনার অভিজ্ঞতা শেয়ার করুন এবং পর্যালোচনা অনুমোদনের পরে আপনার বিকাশ/নগদ একাউন্টে ১০০ টাকা পাবেন।',
  rateThisProperty: 'এই বাড়িটি রেট করুন:',
  writeReview: 'আপনার পর্যালোচনা লিখুন:',
  earn100Banner: '১০০ টাকা আয় করুন!',
  earn100Submit: 'আপনার সৎ পর্যালোচনা জমা দিন এবং ২৪ ঘণ্টার মধ্যে ১০০ টাকা পাবেন।',
  submitAndEarn: 'পর্যালোচনা জমা দিন ও ১০০ টাকা আয় করুন',
  yourRating: 'আপনার রেটিং:',
  yourReview: 'আপনার পর্যালোচনা:',
  rewardCredited: 'পুরস্কার জমা হয়েছে!',
  rewardCreditedDesc: 'আপনার মোবাইল ওয়ালেটে ১০০ টাকা জমা হয়েছে।',
  editReview: 'পর্যালোচনা সম্পাদনা করুন',
  tenantRating: 'ভাড়াটের রেটিং:',
  reviewText: 'পর্যালোচনা:',
  receivedBDT: 'আপনি বাসাবাড়ি থেকে ১০০ টাকা পেয়েছেন',

  // ── Agreements ────────────────────────────────────────────────────────────
  writtenAgreementsTitle: 'লিখিত চুক্তি',
  digitalAgreements: 'ডিজিটাল চুক্তি',
  digitalAgreementsDesc: 'আপনার সমস্ত ভাড়া চুক্তি নিরাপদে সংরক্ষিত। যেকোনো সময় দেখুন, ডাউনলোড করুন বা শেয়ার করুন।',
  activeStatus: 'সক্রিয়',
  expiredStatus: 'মেয়াদোত্তীর্ণ',
  landlordLabel: 'বাড়িওয়ালা',
  tenantLabel: 'ভাড়াটে',
  startDate: 'শুরুর তারিখ',
  endDate: 'শেষ তারিখ',
  signedOn: 'স্বাক্ষরের তারিখ',
  monthlyRentLabel: 'মাসিক ভাড়া',
  advancePayment: 'অগ্রিম পেমেন্ট',
  securityDeposit: 'নিরাপত্তা জামানত',
  keyTerms: 'মূল শর্তাবলী',
  viewFull: 'সম্পূর্ণ চুক্তি দেখুন',
  downloadPdf: 'পিডিএফ ডাউনলোড করুন',

  // ── Booked Flats ──────────────────────────────────────────────────────────
  bookedProperties: 'সংরক্ষিত বাড়িসমূহ',
  savedPropertiesTitle: 'আপনার সংরক্ষিত বাড়িসমূহ',
  savedPropertiesDesc: 'আপনি যে বাড়িগুলোতে আগ্রহ দেখিয়েছেন। অ্যাপের মাধ্যমে সরাসরি মালিকের সাথে যোগাযোগ করুন।',
  ownerContact: 'মালিকের যোগাযোগ',
  saved: 'সংরক্ষিত',
  viewDetails: 'বিস্তারিত দেখুন',

  // ── Legal Rights ──────────────────────────────────────────────────────────
  legalRightsTitle: 'আইনি অধিকার',
  tenantRightsTitle: 'ভাড়াটে হিসেবে আপনার অধিকার',
  landlordRightsTitle: 'বাড়িওয়ালা হিসেবে আপনার অধিকার',
  legalDesc: 'বাংলাদেশের ভাড়া আইনের অধীনে আপনার আইনি অধিকার ও সুরক্ষা জানুন',
  importantInfo: 'গুরুত্বপূর্ণ তথ্য',
  legalNote: 'এই অধিকারগুলো বাংলাদেশের ভবন ভাড়া নিয়ন্ত্রণ আইন ও সংশ্লিষ্ট আবাসন বিধিমালার উপর ভিত্তি করে। সর্বদা চুক্তি লিখিতভাবে নথিভুক্ত করুন।',
  needLegal: 'আইনি সহায়তা প্রয়োজন?',
  needLegalDesc: 'আপনি যদি কোনো আইনি সমস্যার সম্মুখীন হন, একজন আইনজীবীর সাথে পরামর্শ করুন বা আপনার এলাকার ভাড়া নিয়ন্ত্রক অফিসে যোগাযোগ করুন।',
  contactSupport: 'সহায়তায় যোগাযোগ করুন',

  // ── Move In ───────────────────────────────────────────────────────────────
  moveInService: 'স্থানান্তর সেবা',
  moveInDetails: 'স্থানান্তর বিস্তারিত',
  propertiesViewed: 'আপনি যে বাড়িগুলো দেখেছেন',
  selectPropertyDesc: 'স্থানান্তর প্রক্রিয়া শুরু করতে একটি বাড়ি নির্বাচন করুন',
  helpSettle: 'স্থিতিশীল হতে সহায়তা করুন',
  settleDesc: 'মসৃণ স্থানান্তরের জন্য প্রয়োজনীয় সেবা নির্বাচন করুন',
  electronicsSetup: 'ইলেকট্রনিক্স সেটআপ',
  electronicsDesc: 'টিভি, এসি এবং যন্ত্রপাতির পেশাদার ইনস্টলেশন',
  furnitureTransit: 'আসবাবপত্র পরিবহন',
  furnitureDesc: 'আসবাবপত্রের নিরাপদ স্থানান্তর ও বিন্যাস',
  wifiInstall: 'ওয়াইফাই স্থাপনা',
  wifiDesc: 'হাই-স্পিড ইন্টারনেট সেটআপ ও কনফিগারেশন',
  addIn: 'যোগ করুন',
  added: '✓ যোগ হয়েছে',
  totalCost: 'মোট খরচ:',
  confirmMoveIn: 'স্থানান্তর নিশ্চিত করুন',
  moveInSent: 'স্থানান্তর অনুরোধ পাঠানো হয়েছে!',
  moveInSentDesc: 'আপনার নিশ্চিতকরণ বার্তা {owner}-কে পাঠানো হয়েছে। তাদের উত্তরের জন্য চ্যাটবক্স দেখুন।',
  goToChatbox: 'চ্যাটবক্সে যান',

  // ── Premium Payment ───────────────────────────────────────────────────────
  premiumSubscription: 'প্রিমিয়াম সাবস্ক্রিপশন',
  premiumAnnual: 'বাসাবাড়ি প্রিমিয়াম — বার্ষিক সাবস্ক্রিপশন',
  subscriptionPeriod: 'সাবস্ক্রিপশন মেয়াদ:',
  oneYear: '১ বছর',
  amount: 'পরিমাণ:',
  selectPaymentMethod: 'পেমেন্ট পদ্ধতি নির্বাচন করুন',
  paymentInfo: 'পেমেন্ট তথ্য',
  mobileNumber: 'মোবাইল নম্বর',
  txIdLabel: 'লেনদেন আইডি',
  payAmount: 'পরিশোধ করুন',
  paymentSuccess: 'পেমেন্ট সফল হয়েছে!',
  welcomePremium: 'বাসাবাড়ি প্রিমিয়ামে স্বাগতম!',
  premiumActive: 'আপনার প্রিমিয়াম সাবস্ক্রিপশন এখন সক্রিয়। আগামী ১২ মাস সমস্ত এক্সক্লুসিভ সুবিধা উপভোগ করুন।',

  // ── Payment Interface ─────────────────────────────────────────────────────
  makePayment: 'পেমেন্ট করুন',
  paymentDetailsTitle: 'পেমেন্টের বিবরণ',
  property: 'বাড়ি',
  paymentType: 'পেমেন্টের ধরন',
  dueDate: 'পরিশোধের তারিখ',
  amountLabel: 'পরিমাণ:',
  accountNumber: 'একাউন্ট নম্বর',
  pin: 'পিন / পাসওয়ার্ড',
  enterPin: 'আপনার পিন দিন',
  paymentReceivedMsg: 'সফলভাবে পরিশোধ করা হয়েছে',

  // ── My Posts ──────────────────────────────────────────────────────────────
  myPostsTitle: 'আমার পোস্ট',
  verifiedTab: 'যাচাইকৃত',
  pendingTab: 'মুলতুবি',
  unverifiedTab: 'অযাচাইকৃত',
  views: 'ভিউ',
  inquiries: 'অনুসন্ধান',
  postedOn: 'পোস্ট হয়েছে',
  edit: 'সম্পাদনা',
  noVerifiedPosts: 'কোনো যাচাইকৃত পোস্ট নেই',
  noVerifiedDesc: 'আপনার যাচাইকৃত পোস্টগুলো এখানে দেখাবে',
  noPendingPosts: 'কোনো মুলতুবি পোস্ট নেই',
  noPendingDesc: 'যাচাইয়ের অপেক্ষায় থাকা পোস্টগুলো এখানে দেখাবে',
  noUnverifiedPosts: 'কোনো অযাচাইকৃত পোস্ট নেই',
  noUnverifiedDesc: 'আপনার বিনামূল্যে পোস্টগুলো এখানে দেখাবে',
  underReview: 'পর্যালোচনাধীন',
};

export type TranslationKeys = keyof typeof en;

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKeys) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('en');
  const translations = lang === 'en' ? en : bn;
  const t = (key: TranslationKeys) => translations[key] ?? en[key];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
